In [8]:
import numpy as np
maxr = 550
minr = 200
maxtheta = 360
mintheta = 0
rstep = 1.0
thetastep = 360.0/(180*8)
H = int((maxr-minr)/rstep)+1
W =  int((maxtheta-mintheta)/thetastep)+1
O = np.zeros((H,W))

In [9]:
H

351

In [10]:
W

1441

In [11]:
O

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:
r = np.linspace(minr,maxr,H)
r

array([200., 201., 202., 203., 204., 205., 206., 207., 208., 209., 210.,
       211., 212., 213., 214., 215., 216., 217., 218., 219., 220., 221.,
       222., 223., 224., 225., 226., 227., 228., 229., 230., 231., 232.,
       233., 234., 235., 236., 237., 238., 239., 240., 241., 242., 243.,
       244., 245., 246., 247., 248., 249., 250., 251., 252., 253., 254.,
       255., 256., 257., 258., 259., 260., 261., 262., 263., 264., 265.,
       266., 267., 268., 269., 270., 271., 272., 273., 274., 275., 276.,
       277., 278., 279., 280., 281., 282., 283., 284., 285., 286., 287.,
       288., 289., 290., 291., 292., 293., 294., 295., 296., 297., 298.,
       299., 300., 301., 302., 303., 304., 305., 306., 307., 308., 309.,
       310., 311., 312., 313., 314., 315., 316., 317., 318., 319., 320.,
       321., 322., 323., 324., 325., 326., 327., 328., 329., 330., 331.,
       332., 333., 334., 335., 336., 337., 338., 339., 340., 341., 342.,
       343., 344., 345., 346., 347., 348., 349., 35

In [14]:
r = np.tile(r,(W,1))
r

array([[200., 201., 202., ..., 548., 549., 550.],
       [200., 201., 202., ..., 548., 549., 550.],
       [200., 201., 202., ..., 548., 549., 550.],
       ...,
       [200., 201., 202., ..., 548., 549., 550.],
       [200., 201., 202., ..., 548., 549., 550.],
       [200., 201., 202., ..., 548., 549., 550.]])

In [15]:
r = np.transpose(r)
r

array([[200., 200., 200., ..., 200., 200., 200.],
       [201., 201., 201., ..., 201., 201., 201.],
       [202., 202., 202., ..., 202., 202., 202.],
       ...,
       [548., 548., 548., ..., 548., 548., 548.],
       [549., 549., 549., ..., 549., 549., 549.],
       [550., 550., 550., ..., 550., 550., 550.]])

In [16]:
theta = np.linspace(mintheta,maxtheta,W)
theta

array([0.0000e+00, 2.5000e-01, 5.0000e-01, ..., 3.5950e+02, 3.5975e+02,
       3.6000e+02])

In [17]:
theta = np.tile(theta,(H,1))
theta

array([[0.0000e+00, 2.5000e-01, 5.0000e-01, ..., 3.5950e+02, 3.5975e+02,
        3.6000e+02],
       [0.0000e+00, 2.5000e-01, 5.0000e-01, ..., 3.5950e+02, 3.5975e+02,
        3.6000e+02],
       [0.0000e+00, 2.5000e-01, 5.0000e-01, ..., 3.5950e+02, 3.5975e+02,
        3.6000e+02],
       ...,
       [0.0000e+00, 2.5000e-01, 5.0000e-01, ..., 3.5950e+02, 3.5975e+02,
        3.6000e+02],
       [0.0000e+00, 2.5000e-01, 5.0000e-01, ..., 3.5950e+02, 3.5975e+02,
        3.6000e+02],
       [0.0000e+00, 2.5000e-01, 5.0000e-01, ..., 3.5950e+02, 3.5975e+02,
        3.6000e+02]])